/**
 * Copyright (C) 2014-2016 LinkedIn Corp. (pinot-core@linkedin.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.linkedin.pinot.core.segment.creator;

import org.apache.commons.lang3.ArrayUtils;


/**
 */

public class ColumnIndexCreationInfo {
  private final boolean createDictionary;
  private final Object min;
  private final Object max;
  private final Object sortedUniqueElementsArray;
  private final ForwardIndexType forwardIndexType;
  private final InvertedIndexType invertedIndexType;
  private boolean isSorted;
  private final boolean hasNulls;
  private final int totalNumberOfEntries;
  private final int maxNumberOfMutiValueElements;
  private Object defaultNullValue;
  private boolean isAutoGenerated;

  public ColumnIndexCreationInfo(boolean createDictionary, Object min, Object max, Object sortedArray, ForwardIndexType forwardIndexType,
      InvertedIndexType invertedIndexType, boolean isSortedColumn, boolean hasNulls, int totalNumberOfEntries,
      int maxNumberOfMultiValueElements, Object defaultNullValue, boolean isAutoGenerated) {
    this.createDictionary = createDictionary;
    this.min = min;
    this.max = max;
    this.sortedUniqueElementsArray = sortedArray;
    this.forwardIndexType = forwardIndexType;
    this.invertedIndexType = invertedIndexType;
    this.isSorted = isSortedColumn;
    this.hasNulls = hasNulls;
    this.totalNumberOfEntries = totalNumberOfEntries;
    this.maxNumberOfMutiValueElements = maxNumberOfMultiValueElements;
    this.defaultNullValue = defaultNullValue;
    this.isAutoGenerated = isAutoGenerated;
  }

  public int getMaxNumberOfMutiValueElements() {
    return maxNumberOfMutiValueElements;
  }

  public boolean isCreateDictionary() {
    return createDictionary;
  }

  public Object getMin() {
    return min;
  }

  public Object getMax() {
    return max;
  }

  public Object getSortedUniqueElementsArray() {
    return sortedUniqueElementsArray;
  }

  public ForwardIndexType getForwardIndexType() {
    return forwardIndexType;
  }

  public InvertedIndexType getInvertedIndexType() {
    return invertedIndexType;
  }

  public boolean isSorted() {
    return isSorted;
  }

  public void setSorted(boolean value) {
    isSorted = value;
  }

  public boolean hasNulls() {
    return hasNulls;
  }

  public int getTotalNumberOfEntries() {
    return totalNumberOfEntries;
  }

  public int getDistinctValueCount() {
    return ArrayUtils.getLength(sortedUniqueElementsArray);
  }
  
  public boolean isAutoGenerated() {
    return isAutoGenerated;
  }
  
  public Object getDefaultNullValue() {
    return defaultNullValue;
  }
  
}
